/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sampai desu (https://sketchfab.com/Sampai_desu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-cabin-on-the-island-d5a98f753465483d9e9333706435e682
Title: [FREE] Cabin on the island
*/


import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/island.glb";


const Island = (props) => {
    const islandref = useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
    <a.group ref={islandref} {...props} >
        <mesh
          geometry={nodes.Cylinder001_zemlia_0.geometry}
          material={materials.zemlia}
          position={[-5.702, -7.35, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube010_kamni_0.geometry}
          material={materials.kamni}
          position={[-59.517, -28.441, 73.597]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane_voda4_0.geometry}
          material={materials.voda4}
          position={[-5.495, -40.336, -1.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={179.536}
        />
        <mesh
          geometry={nodes.Cylinder008_stvol_dereva_0.geometry}
          material={materials.stvol_dereva}
          position={[-33.68, 40.551, -34.685]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube016_dom_0.geometry}
          material={materials.material}
          position={[0.097, 7.137, 3.326]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube015_most_0.geometry}
          material={materials.most}
          position={[61.626, -27.542, -0.049]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder010_bochka_0.geometry}
          material={materials.bochka}
          position={[-20.303, 4.805, -15.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder012_iashik_krishka_0.geometry}
          material={materials.iashik_krishka}
          position={[-24.477, 3.493, -10.127]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder002_zemlia2_0.geometry}
          material={materials.zemlia2}
          position={[-5.702, -7.35, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane002_elka_krona4_0.geometry}
          material={materials.elka_krona4}
          position={[-4.105, 156.493, -63.304]}
          rotation={[-2.32, 0.067, -3.103]}
          scale={[1.432, 5.284, 10.019]}
        />
        <mesh
          geometry={nodes.Plane016_elka_krona3_0.geometry}
          material={materials.elka_krona3}
          position={[-26.119, 173.419, -32.594]}
          rotation={[-0.918, -0.297, -0.281]}
          scale={[1.432, 5.284, 10.019]}
        />
        <mesh
          geometry={nodes.Plane014_grass1_0.geometry}
          material={materials.grass1}
          position={[37.802, -14.162, -0.878]}
          rotation={[-0.011, 0.098, -0.053]}
          scale={1.577}
        />
    </a.group>
  );
}

export default Island;

