import { React, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import planeScene from "../assets/3d/plane.glb"
import { a } from '@react-spring/three'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Miroshkins (https://sketchfab.com/miroshkins)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-plane-77a7e55aa20f4b6594ca385c7dcbeeaf
Title: Paper Plane
*/


const Plane = (...props) => {
    const planeRef = useRef();
  const { nodes, materials, scene, animations } = useGLTF(planeScene);
  const { actions } = useAnimations(animations, planeRef)
  return (
    <a.group ref = {planeRef} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material001_0.geometry}
        material={materials["Material.001"]}
        // X, Y, Z axis
        position={[0, -2.2, -2]}
        rotation={[-Math.PI / 3.2, 0, 0]}
        scale={1}
      />
    </a.group>
  );
}

export default Plane